# Generated by Django 3.1.8 on 2023-05-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='re_password',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
