# Generated by Django 3.1.8 on 2023-05-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20230506_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='re_password',
            field=models.CharField(default='NUll', max_length=100),
        ),
    ]
