# Generated by Django 3.1.8 on 2023-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20230506_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='re_password',
            field=models.CharField(max_length=100),
        ),
    ]
