# Generated by Django 3.1.8 on 2023-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20230506_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(default=0),
        ),
    ]
