# Generated by Django 3.1.8 on 2023-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20230507_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
    ]
