# Generated by Django 3.1.8 on 2023-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20230510_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
