# Generated by Django 3.1.8 on 2023-05-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20230510_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_authorised_to_mobile_banking',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
