# Generated by Django 3.1.8 on 2023-05-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_customer_phone_authorised_to_mobile_banking'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_authorised_to_mobile_banking',
            field=models.CharField(default='NULL', max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_authorised_to_mobile_banking',
            field=models.CharField(max_length=100),
        ),
    ]
