# Generated by Django 3.1.8 on 2023-05-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20230512_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_authorised_to_mobile_banking',
        ),
    ]
