# Generated by Django 4.2.1 on 2023-05-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_account_phone_authorised_to_mobile_banking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bkash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_authorised_to_mobile_banking', models.CharField(default='NULL', max_length=11)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
